"""Módulo de modelos de dados."""

from app.models.models import (
    Atendimento,
    AtendimentoCreate,
    AtendimentoRead,
    AtendimentoUpdate,
    Categoria,
    CategoriaCreate,
    CategoriaRead,
    CategoriaUpdate,
    Denuncia,
    DenunciaCategoria,
    DenunciaCreate,
    DenunciaRead,
    DenunciaReadFull,
    DenunciaUpdate,
    Document,
    DocumentRead,
    Localizacao,
    LocalizacaoCreate,
    LocalizacaoRead,
    LocalizacaoUpdate,
    PrioridadeEnum,
    SituacaoEnum,
    Status,
    StatusCreate,
    StatusRead,
    StatusUpdate,
    Usuario,
    UsuarioCreate,
    UsuarioRead,
    UsuarioReadWithDenuncias,
    UsuarioUpdate,
)

__all__ = [
    "Atendimento", "AtendimentoCreate", "AtendimentoRead", "AtendimentoUpdate",
    "Categoria", "CategoriaCreate", "CategoriaRead", "CategoriaUpdate",
    "Denuncia", "DenunciaCategoria", "DenunciaCreate", "DenunciaRead",
    "DenunciaReadFull", "DenunciaUpdate",
    "Document", "DocumentRead",
    "Localizacao", "LocalizacaoCreate", "LocalizacaoRead", "LocalizacaoUpdate",
    "PrioridadeEnum", "SituacaoEnum",
    "Status", "StatusCreate", "StatusRead", "StatusUpdate",
    "Usuario", "UsuarioCreate", "UsuarioRead", "UsuarioReadWithDenuncias", "UsuarioUpdate",
]
